"""init schema

Revision ID: ea24e2355e99
Revises: 
Create Date: 2025-04-09 14:44:23.143027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea24e2355e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer_odds_parsed',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id_pinnacle', sa.BigInteger(), nullable=False),
    sa.Column('match_id_lobbet', sa.BigInteger(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('sport_name', sa.String(), nullable=False),
    sa.Column('league_pinnacle', sa.String(), nullable=True),
    sa.Column('league_lobbet', sa.String(), nullable=True),
    sa.Column('market_type', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('value_pinnacle', sa.Float(), nullable=True),
    sa.Column('value_lobbet', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('raw_created_at', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyzer_keyhash_created', 'analyzer_odds_parsed', ['key_hash', 'created_at'], unique=False)
    op.create_index('ix_analyzer_match_created', 'analyzer_odds_parsed', ['match_id_pinnacle', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('live_odds_parsed',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('sport_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_liveodds_keyhash_created', 'live_odds_parsed', ['key_hash', 'created_at'], unique=False)
    op.create_index('ix_liveodds_match_created', 'live_odds_parsed', ['match_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_liveodds_match_created', table_name='live_odds_parsed')
    op.drop_index('ix_liveodds_keyhash_created', table_name='live_odds_parsed')
    op.drop_table('live_odds_parsed')
    op.drop_index('ix_analyzer_match_created', table_name='analyzer_odds_parsed')
    op.drop_index('ix_analyzer_keyhash_created', table_name='analyzer_odds_parsed')
    op.drop_table('analyzer_odds_parsed')
    # ### end Alembic commands ###
